### Create VAT Rates
POST http://localhost:8080/api/vat-rates
Content-Type: application/json

{
  "name": "dph - snizena",
  "rate": 0.11
}

###
// @sleep 30

###
POST http://localhost:8080/api/vat-rates
Content-Type: application/json

{
  "name": "dph - potraviny",
  "rate": 0.15
}

###
// @sleep 30

###
POST http://localhost:8080/api/vat-rates
Content-Type: application/json

{
  "name": "dph - standartni",
  "rate": 0.21
}

###
// @sleep 30

### Create Ingredients
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "Mouka",
  "unit": "kg",
  "lossCleaningFactor": 0.05,
  "lossUsageFactor": 0.02,
  "vatRateId": 1
}
###
// @sleep 30

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "Mozzarella",
  "unit": "g",
  "lossCleaningFactor": 0.01,
  "lossUsageFactor": 0.03,
  "vatRateId": 1
}
###
// @sleep 30

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "Rajčatová omáčka",
  "unit": "g",
  "lossCleaningFactor": 0.0,
  "lossUsageFactor": 0.05,
  "vatRateId": 1
}
###
// @sleep 30

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "Bazalka",
  "unit": "g",
  "lossCleaningFactor": 0.1,
  "lossUsageFactor": 0.1,
  "vatRateId": 1
}
###
// @sleep 30

###
POST http://localhost:8080/api/ingredients
Content-Type: application/json

{
  "name": "Šunka",
  "unit": "g",
  "lossCleaningFactor": 0.15,
  "lossUsageFactor": 0.1,
  "vatRateId": 1
}
###
// @sleep 30

### Create Pizza
POST http://localhost:8080/api/pizzas
Content-Type: application/json

{
  "name": "Margherita",
  "description": "Klasická pizza s rajčatovou omáčkou a mozzarellou"
}
###
// @sleep 30

###
POST http://localhost:8080/api/pizzas
Content-Type: application/json

{
  "name": "Prosciutto",
  "description": "Pizza se šunkou, rajčatovou omáčkou a mozzarellou"
}
###
// @sleep 30

### Add Ingredients to Pizzas (Recipes)
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 1,
  "quantity": 0.25
}
###
// @sleep 30

###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 2,
  "quantity": 110
}
###
// @sleep 30

###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 3,
  "quantity": 80
}
###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 4,
  "quantity": 5
}
###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 1,
  "quantity": 0.25
}
###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 2,
  "quantity": 110
}
###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 3,
  "quantity": 80
}
###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 5,
  "quantity": 90
}

###
// @sleep 30


### Create Inventory Snapshots
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 1,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 100.0,
  "note": "Start"
}
###
// @sleep 30
###
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 2,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 5000.0,
  "note": "Start"
}
###
// @sleep 30
###
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 3,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 3000.0,
  "note": "Start"
}
###
// @sleep 30
###
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 4,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 200.0,
  "note": "Start"
}
###
// @sleep 30
###
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 5,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 4000.0,
  "note": "Start"
}
###
// @sleep 30
### Create default dish size (Base)
POST http://localhost:8080/api/dish-sizes
Content-Type: application/json

{
  "name": "mala/base",
  "factor": 1.0
}
###
### Create large size
POST http://localhost:8080/api/dish-sizes
Content-Type: application/json

{
  "name": "Velká",
  "factor": 1.7
}

### Přidání dodavatele
POST http://localhost:8080/api/suppliers
Content-Type: application/json

{
  "name": "Nowaco s.r.o.",
  "contactInfo": "kontakt@nowaco.cz"
}

###
POST http://localhost:8080/api/suppliers
Content-Type: application/json

{
"name": "Cortelazzi s.r.o.",
"contactInfo": "kontakt@cortellazi.cz"
}