### Create Inventory Snapshots
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 1,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 100.0,
  "note": "Start"
}
###
// @sleep 30
###
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 2,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 5000.0,
  "note": "Start"
}
###
// @sleep 30
###
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 3,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 3000.0,
  "note": "Start"
}
###
// @sleep 30
###
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 4,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 200.0,
  "note": "Start"
}
###
// @sleep 30
###
POST http://localhost:8080/api/inventory/snapshot
Content-Type: application/json

{
  "ingredientId": 5,
  "timestamp": "31/05/2025 14",
  "measuredQuantity": 4000.0,
  "note": "Start"
}
###
// @sleep 30