### Add Ingredients to Pizzas (Recipes)
POST http://localhost:8080/api/menuItems/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 1,
  "quantity": 0.25
}
###
// @sleep 30

###
POST http://localhost:8080/api/menuItems/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 2,
  "quantity": 110
}
###
// @sleep 30

###
POST http://localhost:8080/api/menuItems/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 3,
  "quantity": 80
}
###
// @sleep 30
###
POST http://localhost:8080/api/menuItems/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 4,
  "quantity": 5
}
###
// @sleep 30
###
POST http://localhost:8080/api/menuItems/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 1,
  "quantity": 0.25
}
###
// @sleep 30
###
POST http://localhost:8080/api/menuItems/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 2,
  "quantity": 110
}
###
// @sleep 30
###
POST http://localhost:8080/api/menuItems/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 3,
  "quantity": 80
}
###
// @sleep 30
###
POST http://localhost:8080/api/menuItems/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 5,
  "quantity": 90
}

### Bulk Add Recipe to Pizza
// @sleep 30
POST http://localhost:8080/api/menuItems/recipes/bulk
Content-Type: application/json

{
  "pizzaName": "Vesuvio",
  "dishSizeId": 1,
  "ingredients": [
    { "ingredientName": "Mouka", "quantity": 0.25 },
    { "ingredientName": "Mozzarella", "quantity": 110 },
    { "ingredientName": "Rajčatová omáčka", "quantity": 80 },
    { "ingredientName": "Šunka", "quantity": 100 }
  ]
}
###
// @sleep 30
POST http://localhost:8080/api/menuItems/recipes/bulk
Content-Type: application/json

{
  "pizzaName": "Funghi",
  "dishSizeId": 1,
  "ingredients": [
    { "ingredientName": "Mouka", "quantity": 0.25 },
    { "ingredientName": "Mozzarella", "quantity": 110 },
    { "ingredientName": "Rajčatová omáčka", "quantity": 80 },
    { "ingredientName": "Žampiony", "quantity": 120 }
  ]
}