version: '3.8'

services:
  mysql:
    container_name: mysql-ppcstorage
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: CHANGEIT
      MYSQL_DATABASE: ppcstorage
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - spring-demo
    restart: unless-stopped

  maildev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080   # Web UI
      - 1025:1025   # SMTP
    networks:
      - spring-demo
    restart: unless-stopped

  # BE KONFIGURACE

  #  backend:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: ppcstorage-backend
  #    ports:
  #      - 8080:8080
  #    environment:
  #      SPRING_PROFILES_ACTIVE: docker
  #    networks:
  #      - spring-demo
  #    depends_on:
  #      - mysql
  #      - maildev

  # FE KONFIGURACE
  #
  backend:
    image: leorickk/pizzacipollastorage-backend:latest
    container_name: ppcstorage-backend
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - spring-demo
    depends_on:
      - mysql
      - maildev
    restart: unless-stopped

  frontend:
    image: leorickk/zradlo-fe:latest
    container_name: zradlo-fe
    ports:
      - 3000:3000
    networks:
      - spring-demo
    restart: unless-stopped


networks:
  spring-demo:
    driver: bridge

volumes:
  mysql_data: