### Get all VAT rates
GET http://localhost:8080/api/vat-rates

### Get all ingredients
GET http://localhost:8080/api/ingredients

### Get current inventory status
GET http://localhost:8080/api/inventory/current-status

### Get all pizzas
GET http://localhost:8080/api/pizzas

### Get All Dish Sizes
GET http://localhost:8080/api/dish-sizes

### Get All Suppliers
GET http://localhost:8080/api/suppliers

### Získání posledních 10 faktur od nejmladší po nejstarší
GET http://localhost:8080/api/purchase-invoices

### Získání ingredience podle jména nebo aliasu
GET http://localhost:8080/api/ingredients/by-name/sugo

### Neexistující ingredience
GET http://localhost:8080/api/ingredients/by-name/neexistujici