### Přidání více aliasů najednou
POST http://localhost:8080/api/ingredient-aliases/batch
Content-Type: application/json

[
  { "aliasName": "rajčatova omacka", "ingredientId": 3 },
  { "aliasName": "rajcatová", "ingredientId": 3 },
  { "aliasName": "rajcatova", "ingredientId": 3 },
  { "aliasName": "sugo", "ingredientId": 3 },
  { "aliasName": "sugo di pomodoro", "ingredientId": 3 },
  { "aliasName": "paradajkova omacka", "ingredientId": 3 },
  { "aliasName": "paradajkova", "ingredientId": 3 },
  { "aliasName": "tomato sauce", "ingredientId": 3 },
  { "aliasName": "omacka z rajcat", "ingredientId": 3 },
  { "aliasName": "z rajcat", "ingredientId": 3 }
]

### Add Ingredients to Pizzas (Recipes)
// @sleep 30
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 1,
  "quantity": 0.25
}

###
// @sleep 30

###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 2,
  "quantity": 110
}

###
// @sleep 30

###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 3,
  "quantity": 80
}

###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 1,
  "ingredientId": 4,
  "quantity": 5
}

###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 1,
  "quantity": 0.25
}

###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 2,
  "quantity": 110
}

###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 3,
  "quantity": 80
}

###
// @sleep 30
###
POST http://localhost:8080/api/pizzas/recipes
Content-Type: application/json

{
  "pizzaId": 2,
  "ingredientId": 5,
  "quantity": 90
}